# Generated by Django 6.0.4 on 2026-05-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('instructor', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
