# Generated by Django 6.0.4 on 2026-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('numOfMonths', models.IntegerField()),
                ('track', models.CharField(max_length=20)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
