# Generated by Django 6.0.4 on 2026-05-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='track',
            field=models.TextField(),
        ),
    ]
